# Site settings
title: Things I Like. In
email:
description: > # this means to ignore newlines until "baseurl:"
  Things I Like. In (TIL). Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thingsilike.in" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
exclude: [vendor]
