# Site settings
title: Things I Like. In Words
permalink: /:year/:month/:title/
email: levent@purebreeze.com
description: > # this means to ignore newlines until "baseurl:"
  Things I Like In Words.
  TIL.
  This is a personal blog
  to get me in the habit of writing words
  as opposed to only snapping photos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thingsilike.in" # the base hostname & protocol for your site
twitter_username: lebreeze
github_username: levent

# Build settings
markdown: kramdown
exclude: [vendor]
gems:
  - jekyll-sitemap
